### PR TITLE
IronicInspector: Remove unused IronicPythonAgentImage

### PR DESCRIPTION
**Pull request by kajinamit**

### CODE REVIEW

**Review by hjensas — COMMENTED** [review]
Ugh, this does not look right. What is placing IPA images in Inspectors http folder?

I get the feeling we need to add an initcontainer using the IPA image in inspector instead.

pkg/ironicinspector/initcontainer.go
pkg/ironicinspector/statefulset.go#L265

@steveb Am I missing something related to the change to use IPA image instead of the http_get script we had earlier?

**Comment by hjensas** [comment]
> Ugh, this does not look right. What is placing IPA images in Inspectors http folder?
> 
> I get the feeling we need to add an initcontainer using the IPA image in inspector instead.
> 
> pkg/ironicinspector/initcontainer.go pkg/ironicinspector/statefulset.go#L265
> 
> @steveb Am I missing something related to the change to use IPA image instead of the http_get script we had earlier?

I created https://github.com/openstack-k8s-operators/ironic-operator/pull/328 - I think we need that to ensure IPA is copied to Inspectors HTTP server.

**Comment by kajinamit** [comment]
I'm closing this in favor of https://github.com/openstack-k8s-operators/ironic-operator/pull/328 .

**Pull request closed without merging**
