### PR TITLE
Revert ironic-inspector default image

### PR DESCRIPTION
**Pull request by stuggi**
Jira: [OSPRH-4220](https://issues.redhat.com//browse/OSPRH-4220)

### CODE REVIEW

**Comment by stuggi** [comment]
quay.io/podified-antelope-centos9/openstack-ironic-inspector:current-podified is not yet updated with change from https://github.com/openstack-k8s-operators/tcib/pull/126

**Comment by stuggi** [comment]
finally new image with httpd available at https://quay.io/repository/podified-antelope-centos9/openstack-ironic-inspector?tab=tags&tag=latest

**Review by steveb — APPROVED** [review]
/lgtm

**Pull request merged**
