### PR TITLE
Enable ginkgolinter

### PR DESCRIPTION
**Pull request by bshewale**

### CODE REVIEW

**Comment by bshewale** [comment]
This PR is depends on https://github.com/openshift/release/pull/38499

**Review by hjensas — COMMENTED** [review]
AFICT this is failing because it is using too old ci/golangci-lint:v1.48.0 - we need v0.51.1 or later.

Logs:
```
INFO[2023-04-19T11:58:21Z] Tagging ci/golangci-lint:v1.48.0 into pipeline:golangci-lint. 
INFO[2023-04-19T11:58:22Z] Executing test golangci                      
INFO[2023-04-19T11:58:35Z] Logs for container test in pod golangci:     
INFO[2023-04-19T11:58:35Z] level=info msg="[config_reader] Config search paths: [./ /home/prow/go/src/github.com/openstack-k8s-operators/ironic-operator /home/prow/go/src/github.com/openstack-k8s-operators /home/prow/go/src/github.com /home/prow/go/src /home/prow/go /home/prow /home /]"
level=info msg="[config_reader] Used config file .golangci.yaml"
level=error msg="Running error: unknown linters: 'ginkgolinter', run 'golangci-lint help linters' to see the list of supported linters" 
```

From what I can see in Makefile and pre-commit-config.yaml we are trying to use v1.52.2

Makefile:
```
test -s $(LOCALBIN)/golangci-lint || curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.51.2
```

.pre-commit-config.yaml:
```
- repo: https://github.com/golangci/golangci-lint
  rev: v1.52.2
  hooks:
    - id: golangci-lint
      args: ["-v"]
```

We may need to add a version here? (But afict from that install.sh script it should use `latest` when nothing is specified.
```
CI_TOOLS_REPO/test-runner/golangci.sh:curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | bash -x -s --
```

**Review by hjensas — APPROVED** [review]
CI looks green. LGTM.

**Pull request merged**
