### PR TITLE
Enable podified zuul jobs against Ironic operator

### PR DESCRIPTION
**Pull request by raukadah**
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1163
Depends-On: https://github.com/openstack-k8s-operators/ironic-operator/pull/397

### CODE REVIEW

**Comment by raukadah** [comment]
Below is the current failure from tempest: https://logserver.rdoproject.org/96/396/bd00af50f42e960a0dd530455ab9f44b82fc9128/github-check/podified-multinode-ironic-deployment/5c54c84/controller/ci-framework-data/tests/tempest/stestr_results.html

**Comment by raukadah** [comment]
recheck after pr update

**Comment by hjensas** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by hjensas** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by viroel** [comment]
@raukadah it would be good to remove the tempest Prow job now, since the zuul job already covers it

**Pull request merged**
