### PR TITLE
[test] validate that TLSInputReadyCondition is ready when cert secret…

### PR DESCRIPTION
**Pull request by stuggi**
…s are set

Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1563

### CODE REVIEW

**Comment by stuggi** [comment]
recheck

**Comment by stuggi** [comment]
recheck

**Comment by stuggi** [comment]
rebased

**Review by abays — APPROVED** [review]
/lgtm

**Comment by abays** [comment]
recheck

**Comment by juliakreger** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck with debug flag

**Comment by marios** [comment]
per slack chat the zuul problem here is because of this line https://github.com/openstack-k8s-operators/ci-framework/blob/af461d60e1e22de0e5c37632f8a1fcdf333bce62/zuul.d/base.yaml#L64

which stops the content provider from running in the layout, this one https://github.com/openstack-k8s-operators/ci-framework/blob/af461d60e1e22de0e5c37632f8a1fcdf333bce62/zuul.d/project-templates.yaml#L46-L48

**Comment by marios** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck noop job

**Review by hjensas — APPROVED** [review]

**Pull request merged**
