### PR TITLE
Convert runlogwatch.sh to use inotifywait

### PR DESCRIPTION
**Pull request by steveb**
This aligns with metal3 runlogwatch.sh[1] which is possible now that inotify-tools package is available[2].

[1] https://github.com/metal3-io/ironic-image/pull/548/files
[2] https://github.com/openstack-k8s-operators/tcib/commit/0795bb902af2199905413cae8593d382618459e8

Jira: [OSPRH-10240](https://issues.redhat.com//browse/OSPRH-10240)

### CODE REVIEW

**Comment by steveb** [comment]
This has been moved to FR3, hold until FR1 is branched

**Comment by steveb** [comment]
This can be reviewed now, fr1 has been branched

**Comment by steveb** [comment]
Ironic images have been promoted
/retest

**Comment by steveb** [comment]
The kuttl failure looks unrelated, the ramdisk-logs.log looks correct[1]. I think this is ready for review @hjensas 

[1] https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openstack-k8s-operators_ironic-operator/484/pull-ci-openstack-k8s-operators-ironic-operator-main-ironic-operator-build-deploy-kuttl/1857159047409569792/artifacts/ironic-operator-build-deploy-kuttl/openstack-k8s-operators-gather/artifacts/must-gather/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-3d1f620ae3617fbd6371f55aa948b34e9daf31a461d3c557cf1a7c2db38d0385/namespaces/ironic-kuttl-tests/pods/ironic-conductor-0/logs/ramdisk-logs.log

**Comment by steveb** [comment]
Oh, inspector ramdisk-logs is failing. A package is needed in a different image https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openstack-k8s-operators_ironic-operator/484/pull-ci-openstack-k8s-operators-ironic-operator-main-ironic-operator-build-deploy-kuttl/1857159047409569792/artifacts/ironic-operator-build-deploy-kuttl/openstack-k8s-operators-gather/artifacts/must-gather/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-3d1f620ae3617fbd6371f55aa948b34e9daf31a461d3c557cf1a7c2db38d0385/namespaces/ironic-kuttl-tests/pods/ironic-inspector-0/logs/ramdisk-logs.log

**Comment by steveb** [comment]
recheck
/retest
inotify-tools is now in quay.io/podified-antelope-centos9/openstack-ironic-inspector:current-podified

**Comment by steveb** [comment]
@hjensas CI is green on this now

**Review by hjensas — APPROVED** [review]
/lgtm

**Pull request merged**
