### PR TITLE
Fix pre-commit findings

### PR DESCRIPTION
**Pull request by gibizer**

### CODE REVIEW

**Comment by gibizer** [comment]
/test ironic-operator-build-deploy

Something is wrong in the CI machinery?
```
Uploading finished
Error from server (InternalError): Internal error occurred: error getting push/pull secrets for service account openstack/builder: serviceaccounts "builder" not found
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2023-03-13T11:47:30Z"}
error: failed to execute wrapped command: exit status 1 
[36mINFO[0m[2023-03-13T11:47:40Z] Step ironic-operator-build-deploy-openstack-k8s-operators-build failed after 1m10s. 
[36mINFO[0m[2023-03-13T11:47:40Z] Step phase test failed after 1m10s.          
[36mINFO[0m[2023-03-13T11:47:40Z] Running multi-stage phase post               
[36mINFO[0m[2023-03-13T11:47:40Z] Running step ironic-operator-build-deploy-openstack-k8s-operators-gather. 
[36mINFO[0m[2023-03-13T11:48:00Z] Logs for container test in pod ironic-operator-build-deploy-openstack-k8s-operators-gather: 
[36mINFO[0m[2023-03-13T11:48:00Z] + unset NAMESPACE
+ oc project openstack
Now using project "openstack" on server "https://api.oko-08.oooci.ccitredhat.com:6443".
+ oc logs ceph
Error from server (NotFound): pods "ceph" not found
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2023-03-13T11:47:50Z"}
error: failed to execute wrapped command: exit status 1 
```

**Comment by hjensas** [comment]
/test ironic-operator-build-deploy

* could not run steps: step ironic-operator-build-deploy failed: failed to wait for the created cluster claim to become ready: timed out waiting for the condition

**Pull request merged**
