### PR TITLE
Refactor type definitions using templates

### PR DESCRIPTION
**Pull request by kajinamit**
This refactors type definitions using templates. Benefit of approach is that we can hide some specs of sub CRs from the top-level Ironic CR, and decrease size and complexity of the resource definition.

This also replaces defaulting in webhook. The problem with using webhook is that the copied default is baked in CR and users should update all fields when they update existing instances.

### CODE REVIEW

**Comment by kajinamit** [comment]
/retest

looks new crd definition is not picked up for some reason ...

**Comment by kajinamit** [comment]
/test ironic-operator-build-deploy-kuttl

github api ratelimit

**Review by hjensas — COMMENTED** [review]
+1, looks good. I don't think we need to allow a separate DB for inspector, if we do it can be a follow up.

**Review by steveb — APPROVED** [review]
/lgtm

**Pull request merged**
