### PR TITLE
Ensure webhook is started

### PR DESCRIPTION
**Pull request by kajinamit**
This ensures webhook is started when controller-manage deployment becomes ready.

### CODE REVIEW

**Comment by kajinamit** [comment]
The error looks strange. might be an consistent issue caused by some dependency bump ?

```
   [FAILED] Unexpected error:
      <*meta.NoKindMatchError | 0xc000121300>: 
      no matches for kind "IngressController" in version "operator.openshift.io/v1"
      {
          GroupKind: {
              Group: "operator.openshift.io",
              Kind: "IngressController",
          },
          SearchedVersions: ["v1"],
      }
  occurred 
```

**Comment by abays** [comment]
> The error looks strange. might be an consistent issue caused by some dependency bump ?
> 
> ```
>    [FAILED] Unexpected error:
>       <*meta.NoKindMatchError | 0xc000121300>: 
>       no matches for kind "IngressController" in version "operator.openshift.io/v1"
>       {
>           GroupKind: {
>               Group: "operator.openshift.io",
>               Kind: "IngressController",
>           },
>           SearchedVersions: ["v1"],
>       }
>   occurred 
> ```

Seems to be passing now?

**Comment by kajinamit** [comment]
> > The error looks strange. might be an consistent issue caused by some dependency bump ?
> > ```
> >    [FAILED] Unexpected error:
> >       <*meta.NoKindMatchError | 0xc000121300>: 
> >       no matches for kind "IngressController" in version "operator.openshift.io/v1"
> >       {
> >           GroupKind: {
> >               Group: "operator.openshift.io",
> >               Kind: "IngressController",
> >           },
> >           SearchedVersions: ["v1"],
> >       }
> >   occurred 
> > ```
> 
> Seems to be passing now?

Yes. I'm unsure how that could happen. I suspect the cluster was unstable and some openshift specific CRs were not registered there. We may need to register the schema explicitly as it comes from openshift, so that we can run the tests in vanilla k8s.

**Comment by hjensas** [comment]
> > > The error looks strange. might be an consistent issue caused by some dependency bump ?
> > > ```
> > >    [FAILED] Unexpected error:
> > >       <*meta.NoKindMatchError | 0xc000121300>: 
> > >       no matches for kind "IngressController" in version "operator.openshift.io/v1"
> > >       {
> > >           GroupKind: {
> > >               Group: "operator.openshift.io",
> > >               Kind: "IngressController",
> > >           },
> > >           SearchedVersions: ["v1"],
> > >       }
> > >   occurred 
> > > ```
> > 
> > 
> > Seems to be passing now?
> 
> Yes. The job passed so I think we are ok to merge this.
> 
> I'm unsure how that could happen. I suspect the cluster was unstable and some openshift specific CRs were not registered there. We may need to register the schema explicitly as it comes from openshift, so that we can run the tests in vanilla k8s.

The IngressController for EnvTest is completely fake, it should be registered/created before tests run.
https://github.com/openstack-k8s-operators/ironic-operator/blob/main/tests/functional/suite_test.go#L199

/lgtm

**Review by hjensas — APPROVED** [review]

**Review by juliakreger — APPROVED** [review]
/lgtm

**Pull request merged**
