### PR TITLE
Add more EnvTest coverage

### PR DESCRIPTION
**Pull request by hjensas**
* Add more test scaffoling
* Cover more config samples
* Add tests for inspector controller

### CODE REVIEW

**Comment by hjensas** [comment]
/test unit

  * could not run steps: step unit failed: failed to create or restart test pod: unable to create pod: Pod "unit" is invalid: spec.containers[0].resources.requests: Invalid value: "2168235294": must be less than or equal to memory limit of 2Gi

**Comment by hjensas** [comment]
/test unit

https://github.com/openshift/release/pull/41053 should resolve previous resource limit issue.

**Review by steveb — APPROVED** [review]
/lgtm

**Pull request merged**
